name: CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      run: |
        npm install
        npm run-script build
      env:
        CI: false
        API_GATEWAY_URI: ${{ secrets.API_GATEWAY_URI }}

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        API_GATEWAY_URI: ${{ secrets.API_GATEWAY_URI }}
        BRANCH: gh-pages
        FOLDER: build
        
